// Feature-local strings. The shared i18n locales are owned elsewhere; this follows the app language.
export type Labels = typeof ja;

const ja = {
  title: "Worker Agents",
  intro:
    "会話エージェントが委譲できる Worker の定義を管理します。draft の承認はあなたの操作でのみ有効になります。",
  loading: "読み込み中…",
  reload: "再読み込み",
  agents: "Worker 一覧",
  noAgents: "Worker はまだありません。",
  origin: { builtin: "標準", user: "ユーザー" } as Record<string, string>,
  enabled: "有効",
  disabled: "無効",
  enableToggle: (id: string) => `有効/無効: ${id}`,
  currentRevision: "現行",
  noCurrent: "承認済みの revision なし",
  draftRevision: "draft",
  purpose: "目的",
  tools: "ツール",
  outputKind: "出力形式",
  revisionNo: (n: number) => `revision ${n}`,
  details: "履歴を表示",
  hideDetails: "履歴を閉じる",
  revisions: "revision 履歴",
  reviewState: {
    draft: "draft",
    approved: "承認済み",
    rejected: "却下",
    superseded: "置換済み",
  } as Record<string, string>,
  created: "作成",
  approve: "draft を承認",
  approveTitle: "この draft を承認しますか？",
  approveNote: "承認すると、この定義が会話エージェントから委譲できるようになります。",
  approveConfirm: "承認する",
  cancel: "キャンセル",
  hash: "定義ハッシュ",
  webSearch: "Web 検索モード",
  modeInline: "inline",
  modeWorker: "worker",
  modeInlineHelp: "inline: 従来どおり会話エージェントが直接検索します。",
  modeWorkerHelp: "worker: Web 検索を Worker に委譲します（より安全）。",
  modeCurrent: "現在の設定",
  modeUnknown: "不明（選択するまで変更されません）",
  tasks: "最近のタスク",
  noTasks: "タスクはまだありません。",
  colProfile: "Worker",
  colState: "状態",
  colDelivery: "配信",
  colFailure: "失敗コード",
  colCreated: "作成",
  colUpdated: "更新",
  cancelTask: "取消",
  cancelTaskLabel: (id: string) => `タスクを取消: ${id}`,
  blocklist: "URL ブロックリスト",
  blocklistNote:
    "登録されたエントリは、あなたが削除するまで永続的に残ります（自動削除・期限切れはありません）。",
  noBlocklist: "ブロックされた URL はありません。",
  colHost: "ホスト",
  colReason: "理由",
  remove: "削除",
  removeLabel: (host: string) => `ブロックを解除: ${host}`,
  create: "draft を作成",
  createToggle: "新しい draft を作成",
  profileId: "profile id（英小文字・数字・_、3〜40 文字）",
  purposeInput: "目的",
  systemContext: "システムコンテキスト",
  inputSchema: "入力スキーマ（JSON）",
  outputSchema: "出力スキーマ（JSON）",
  invalidJson: "JSON として読み取れません。",
  save: "draft を保存",
  saved: "draft を保存しました。",
  toolsField: "ツール",
  none: "なし",
};

const en: Labels = {
  title: "Worker Agents",
  intro:
    "Manage the workers the conversation agent can delegate to. A draft only takes effect when you approve it.",
  loading: "Loading…",
  reload: "Reload",
  agents: "Workers",
  noAgents: "No workers yet.",
  origin: { builtin: "Built-in", user: "User" },
  enabled: "Enabled",
  disabled: "Disabled",
  enableToggle: (id) => `Enable/disable: ${id}`,
  currentRevision: "Current",
  noCurrent: "No approved revision",
  draftRevision: "Draft",
  purpose: "Purpose",
  tools: "Tools",
  outputKind: "Output",
  revisionNo: (n) => `revision ${n}`,
  details: "Show history",
  hideDetails: "Hide history",
  revisions: "Revision history",
  reviewState: {
    draft: "Draft",
    approved: "Approved",
    rejected: "Rejected",
    superseded: "Superseded",
  },
  created: "Created",
  approve: "Approve draft",
  approveTitle: "Approve this draft?",
  approveNote: "Once approved, the conversation agent can delegate to this definition.",
  approveConfirm: "Approve",
  cancel: "Cancel",
  hash: "Definition hash",
  webSearch: "Web search mode",
  modeInline: "inline",
  modeWorker: "worker",
  modeInlineHelp: "inline: the conversation agent searches directly, as before.",
  modeWorkerHelp: "worker: web search is delegated to a worker (safer).",
  modeCurrent: "Current setting",
  modeUnknown: "Unknown (unchanged until you choose)",
  tasks: "Recent tasks",
  noTasks: "No tasks yet.",
  colProfile: "Worker",
  colState: "State",
  colDelivery: "Delivery",
  colFailure: "Failure code",
  colCreated: "Created",
  colUpdated: "Updated",
  cancelTask: "Cancel",
  cancelTaskLabel: (id) => `Cancel task: ${id}`,
  blocklist: "URL blocklist",
  blocklistNote: "Entries stay until you remove them (there is no automatic removal or expiry).",
  noBlocklist: "No blocked URLs.",
  colHost: "Host",
  colReason: "Reason",
  remove: "Remove",
  removeLabel: (host) => `Unblock: ${host}`,
  create: "Create draft",
  createToggle: "Create a new draft",
  profileId: "Profile id (lowercase, digits, _, 3-40 chars)",
  purposeInput: "Purpose",
  systemContext: "System context",
  inputSchema: "Input schema (JSON)",
  outputSchema: "Output schema (JSON)",
  invalidJson: "Not valid JSON.",
  save: "Save draft",
  saved: "Draft saved.",
  toolsField: "Tools",
  none: "none",
};

export function labelsFor(language: string | undefined): Labels {
  return language?.toLowerCase().startsWith("en") ? en : ja;
}

export function formatTime(ms: number, language: string | undefined): string {
  return new Date(ms).toLocaleString(language?.toLowerCase().startsWith("en") ? "en-US" : "ja-JP", {
    dateStyle: "short",
    timeStyle: "medium",
  });
}
