use crate::voice::streaming_asr::contracts::VoiceAsrStreamEvent;
use crate::{database_error, new_id, now_iso, AppState, StartTurnInput};
use rusqlite::{params, Connection};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::collections::BTreeMap;
use std::sync::Arc;
use tauri::ipc::Channel;
include!("audit.d/01.rs");
include!("audit.d/02.rs");
include!("audit.d/03.rs");
