// Generated by s11tnext-cli. Do not edit.
// compilerVersion: 0.1.2
// catalogDigest: sha256:802039fd3241b1e55d145b868ba2db6d23dee602bc4a7c71aa4a3e048f0b351b

import type { CatalogContract } from "s11tnext";
import { createCatalog } from "s11tnext";

export const expectedCatalogDigest = "sha256:802039fd3241b1e55d145b868ba2db6d23dee602bc4a7c71aa4a3e048f0b351b" as const;

export type PromptKey =
  | "codex.read-only"
  | "conversation.respond";

export type PromptValueMap = {
  "codex.read-only": Record<string, never>;
  "conversation.respond": Record<string, never>;
};

export type PromptOutputMap = {
  "codex.read-only": "text";
  "conversation.respond": "text";
};

export type PromptMessageRoleMap = {
  "codex.read-only": "system";
  "conversation.respond": "system";
};

/** @deprecated Use PromptKey. */
export type SystemContextKey = PromptKey;
/** @deprecated Use PromptValueMap. */
export type SystemContextValueMap = PromptValueMap;
/** @deprecated Use PromptOutputMap. */
export type SystemContextOutputMap = PromptOutputMap;

export type AppCatalogContract = CatalogContract<
  PromptKey,
  PromptValueMap,
  PromptOutputMap,
  PromptMessageRoleMap
>;

export function createAppCatalog(artifact: unknown) {
  return createCatalog<AppCatalogContract>(artifact, { expectedCatalogDigest });
}
