import type { MutableRefObject } from "react";
import type { VoiceSettings } from "../../lib/contracts";
import type { VoiceActivityDetector, VoiceActivityObservation } from "../../lib/voiceActivity";
import type { VoiceSessionEvent } from "../../lib/voiceSession";
import type { CommitReason } from "../../lib/generated/voiceAsr";

export type AmbientVoiceCaptureContext = {
  settings: VoiceSettings;
  disposed: MutableRefObject<boolean>;
  listeningEnabled: MutableRefObject<boolean>;
  captureAttempt: MutableRefObject<number>;
  stream: MutableRefObject<MediaStream | null>;
  audioContext: MutableRefObject<AudioContext | null>;
  source: MutableRefObject<MediaStreamAudioSourceNode | null>;
  node: MutableRefObject<AudioWorkletNode | null>;
  flushResolver: MutableRefObject<(() => void) | null>;
  activityDetector: MutableRefObject<VoiceActivityDetector | null>;
  captureLease: MutableRefObject<(() => void) | null>;
  applyEvent: (event: VoiceSessionEvent) => unknown;
  finishSegment: (reason: CommitReason) => void;
  packetFrame: (frame: Float32Array) => void;
  packetCount: () => number;
  clearTranscript: () => void;
  onActivity?: (observation: VoiceActivityObservation) => void;
  nativeCapture?: MutableRefObject<boolean>;
  nativeStop?: MutableRefObject<(() => Promise<void>) | null>;
  bargeInEnabled?: boolean;
  speechIsPlaying?: () => boolean;
  ttsStartedAtMs?: () => number;
  interruptSpeech?: () => void;
};
