//! IPC command list. Kept out of `lib.rs` so the production line budget stays at 800.
//! Expand `saaa_invoke_handler!` at the `Builder::invoke_handler` call site so Tauri command
//! macros resolve in `lib.rs`. One command per line; do not pack multiple commands onto one line.

macro_rules! saaa_invoke_handler {
    () => {
        tauri::generate_handler![
            memory::personal_state::commands::personal_state_snapshot,
            memory::personal_state::commands::personal_source_page,
            memory::personal_state::commands::forget_personal_source,
            memory::personal_state::commands::personal_state_extract_once,
            get_app_snapshot,
            get_voice_profile_snapshot,
            stage_audio_upload,
            save_voice_enrollment_sample,
            set_target_speaker_filter_enabled,
            delete_voice_enrollment_sample,
            delete_voice_profile,
            read_voice_enrollment_sample,
            frontend_ready,
            export_diagnostics,
            persistence::audit::list_audit_events,
            database_backup::backup_database,
            get_situation_snapshot,
            get_situation_review_snapshot,
            set_situation_monitoring,
            report_owned_signal,
            submit_situation_feedback,
            create_situation_calibration_candidate,
            run_situation_calibration,
            decide_situation_calibration,
            clear_situation_history,
            runtime::turns::command::start_turn,
            record_frontend_audit_event,
            cancel_run,
            test_model_provider,
            resolve_service_harness,
            set_provider_api_key,
            delete_provider_api_key,
            get_provider_credential_state,
            start_voice_asr_session,
            append_voice_asr_audio,
            commit_voice_asr_utterance,
            stop_voice_asr_session,
            stop_tts,
            save_settings_documents,
            set_voice_listening_enabled,
            larm_voice::begin_larm_voice_session,
            larm_voice::end_larm_voice_session,
            list_messages,
            generative_ui::history::list_message_window,
            coding::commands::get_coding_settings,
            coding::commands::save_coding_settings,
            coding::commands::probe_coding,
            coding::commands::register_coding_workspace,
            coding::commands::coding_snapshot,
            coding::commands::cancel_coding_job,
            steward::commands::register_steward_goal,
            steward::commands::withdraw_steward_delegation,
            steward::commands::list_steward_tasks,
            generative_ui::get_ui_enabled,
            generative_ui::set_ui_enabled,
            generative_ui::get_ui_instance,
            generative_ui::query_ui_source,
            generative_ui::save_ui_instance_state,
            generative_ui::publish_ui_view,
            generative_ui::search_ui_views,
            generative_ui::archive_ui_view,
            generative_ui::open_ui_view,
            generative_ui::snapshot_ui_view,
            generative_ui::cancel_ui_run,
            get_conversation_voice_policy,
            update_conversation_voice_policy,
            reset_conversation_voice_policy
        ]
    };
}

pub(crate) use saaa_invoke_handler;
