import { useEffect, useRef, useState } from "react";
import type { MeetingSnapshot, VoiceSettings } from "../../lib/contracts";
import { appendMeetingAudioSegment, discardMeeting, meetingPreflight, pauseMeeting, resumeMeeting, saveMeetingTranscript, startMeeting, stopMeeting } from "../../lib/runtime";
import { appendFrames } from "./audio/pcm";

const idle: MeetingSnapshot = { sessionId: null, state: "idle", captureToken: null, entries: 0, capabilities: { microphone: true, systemAudio: false, overlay: false, translation: false }, error: null };
type Line = { sequence: number; text: string };

export function useMeetingSession(voice: VoiceSettings | null, onActiveChanged: (active: boolean) => void, setError: (value: string | null) => void) {
  const [snapshot, setSnapshot] = useState<MeetingSnapshot>(idle); const [transcript, setTranscript] = useState<Line[]>([]); const [elapsed, setElapsed] = useState(0); const [health, setHealth] = useState("idle");
  const snapshotRef = useRef(snapshot); const stream = useRef<MediaStream | null>(null); const context = useRef<AudioContext | null>(null); const source = useRef<MediaStreamAudioSourceNode | null>(null); const node = useRef<AudioWorkletNode | null>(null); const silentGain = useRef<GainNode | null>(null); const frames = useRef<Float32Array[]>([]); const bufferedSamples = useRef(0); const sequence = useRef(0); const started = useRef(0); const sending = useRef(false);
  function applySnapshot(next: MeetingSnapshot) { snapshotRef.current = next; setSnapshot(next); }
  async function cleanup() { node.current?.disconnect(); source.current?.disconnect(); silentGain.current?.disconnect(); stream.current?.getTracks().forEach((track) => track.stop()); stream.current = null; node.current = null; source.current = null; silentGain.current = null; if (context.current) await context.current.close().catch(() => undefined); context.current = null; frames.current = []; bufferedSamples.current = 0; sending.current = false; onActiveChanged(false); }
  useEffect(() => () => { void cleanup(); }, []);
  useEffect(() => { if (snapshot.state !== "active") return; const timer = window.setInterval(() => setElapsed(Math.floor((Date.now() - started.current) / 1_000)), 1_000); return () => window.clearInterval(timer); }, [snapshot.state]);
  async function flush(sampleRate: number) { const current = snapshotRef.current; if (sending.current || bufferedSamples.current < sampleRate * 5 || !current.sessionId || !current.captureToken) return; const samples = appendFrames(new Float32Array(), frames.current); frames.current = []; bufferedSamples.current = 0; sending.current = true; const currentSequence = sequence.current++; try { const result = await appendMeetingAudioSegment({ sessionId: current.sessionId, captureToken: current.captureToken, lane: "microphone", sequence: currentSequence, samples: Array.from(samples), sampleRate, startedAtMs: Date.now() - started.current, durationMs: Math.round(samples.length / sampleRate * 1_000) }); setTranscript((lines) => [...lines, { sequence: currentSequence, text: result.text }]); } catch (cause) { setHealth("degraded"); setError(String(cause)); await pause(); } finally { sending.current = false; void flush(sampleRate); } }
  async function attachCapture() { const device = voice?.inputDeviceId === "default" ? true : { deviceId: { exact: voice?.inputDeviceId } }; const nextStream = await navigator.mediaDevices.getUserMedia({ audio: device }); const nextContext = new AudioContext(); try { await nextContext.audioWorklet.addModule("/audio/meeting-processor.js"); const nextSource = nextContext.createMediaStreamSource(nextStream); const nextNode = new AudioWorkletNode(nextContext, "meeting-processor"); const gain = nextContext.createGain(); gain.gain.value = 0; nextNode.port.onmessage = (event: MessageEvent<Float32Array>) => { frames.current.push(event.data); bufferedSamples.current += event.data.length; if (bufferedSamples.current > nextContext.sampleRate * 15) { setError("MEETING_BACKPRESSURE: Capture paused before unbounded audio buffering."); void pause(); return; } void flush(nextContext.sampleRate); }; nextSource.connect(nextNode); nextNode.connect(gain); gain.connect(nextContext.destination); stream.current = nextStream; context.current = nextContext; source.current = nextSource; node.current = nextNode; silentGain.current = gain; setHealth("ready"); } catch (cause) { nextStream.getTracks().forEach((track) => track.stop()); await nextContext.close().catch(() => undefined); throw cause; } }
  async function start() { if (!voice) return; setError(null); try { const check = await navigator.mediaDevices.getUserMedia({ audio: voice.inputDeviceId === "default" ? true : { deviceId: { exact: voice.inputDeviceId } } }); check.getTracks().forEach((track) => track.stop()); const preflight = await meetingPreflight({ microphoneDeviceId: voice.inputDeviceId, systemAudioEnabled: false, sttModelPath: voice.sttModel, translationEnabled: false }); if (preflight.blockingErrors.length) throw new Error(preflight.blockingErrors.map((error) => error.message).join(" ")); const next = await startMeeting({ sessionId: `meeting_${crypto.randomUUID().replace(/-/g, "")}`, microphoneDeviceId: voice.inputDeviceId, microphoneEnabled: true, systemAudioEnabled: false, sttModelPath: voice.sttModel, translationEnabled: false, persistenceMode: "discard" }); applySnapshot(next); started.current = Date.now(); sequence.current = 0; setElapsed(0); try { await attachCapture(); onActiveChanged(true); } catch (cause) { await stopMeeting(next.sessionId!); await discardMeeting(next.sessionId!); applySnapshot(idle); throw cause; } } catch (cause) { await cleanup(); setError(`Microphone unavailable: ${String(cause)}`); } }
  async function pause() { const sessionId = snapshotRef.current.sessionId; if (!sessionId) return; try { applySnapshot(await pauseMeeting(sessionId)); } finally { await cleanup(); } }
  async function resume() { const sessionId = snapshotRef.current.sessionId; if (!sessionId) return; const next = await resumeMeeting(sessionId); applySnapshot(next); try { await attachCapture(); onActiveChanged(true); } catch (cause) { applySnapshot(await pauseMeeting(sessionId)); await cleanup(); setError(`Microphone unavailable: ${String(cause)}`); } }
  async function stop() { const sessionId = snapshotRef.current.sessionId; if (!sessionId) return; try { applySnapshot(await stopMeeting(sessionId)); } finally { await cleanup(); } }
  async function save() { const sessionId = snapshotRef.current.sessionId; if (!sessionId) return; applySnapshot(await saveMeetingTranscript(sessionId)); setTranscript([]); }
  async function discard() { const sessionId = snapshotRef.current.sessionId; if (!sessionId) return; await discardMeeting(sessionId); applySnapshot(idle); setTranscript([]); }
  return { snapshot, transcript, elapsed, health, start, pause, resume, stop, save, discard };
}
